In [8]:
from osgeo import ogr
import gdal
import matplotlib.pyplot as plt
import numpy as np

In [23]:
# Open a GDAL raster dataset
raster = gdal.Open("F:/works/practical/S2A/cliped/stack.tif")

In [26]:
# Does the raster have metadata?
print (raster.GetMetadata())

{'AREA_OR_POINT': 'Area'}


In [27]:
# How many bands in the image have?
num_bands = raster.RasterCount
print('Number of bands in image: {n}\n'.format(n=num_bands))

Number of bands in image: 4



In [33]:
# How many rows and columns?
rows = raster.RasterYSize
cols = raster.RasterXSize
print('Image size is: {r} rows x {c} columns\n'.format(r=rows, c=cols))

Image size is: 1770 rows x 2607 columns



In [34]:
# Does the raster have a description or metadata?
desc = raster.GetDescription()
metadata = raster.GetMetadata()

print('Raster description: {desc}'.format(desc=desc))
print('Raster metadata:')
print(metadata)
print('\n')

Raster description: F:/works/practical/S2A/cliped/stack.tif
Raster metadata:
{'AREA_OR_POINT': 'Area'}




In [35]:
driver = raster.GetDriver()
print('Raster driver: {d}\n'.format(d=driver.ShortName))

Raster driver: GTiff



In [36]:
# What is the raster's projection?
proj = raster.GetProjection()
print('Image projection:')
print(proj + '\n')

Image projection:
PROJCS["WGS_1984_UTM_Zone_43N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",75],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AUTHORITY["EPSG","32643"]]



In [37]:
# What is the raster's "geo-transform"
gt = raster.GetGeoTransform()
print('Image geo-transform: {gt}\n'.format(gt=gt))

Image geo-transform: (379903.94753758144, 10.0, 0.0, 3509518.713358881, 0.0, -10.0)



In [38]:
# Access the single (blue) band in the  stacked image
blue = raster.GetRasterBand(1)

print(blue)

<osgeo.gdal.Band; proxy of <Swig Object of type 'GDALRasterBandShadow *' at 0x000001A49D08E300> >


In [39]:
# What is the band's datatype?
datatype = blue.DataType
print('Band datatype: {dt}'.format(dt=blue.DataType))

Band datatype: 6


In [14]:
datatype_name = gdal.GetDataTypeName(blue.DataType)
print('Band datatype: {dt}'.format(dt=datatype_name))

Band datatype: UInt32


In [40]:
# We can also ask how much space does this datatype take up
bytes = gdal.GetDataTypeSize(blue.DataType)
print('Band datatype size: {b} bytes\n'.format(b=bytes))

Band datatype size: 32 bytes



In [41]:
# blue band statistics i.e. mean , median, min, max values?
band_max, band_min, band_mean, band_stddev = blue.GetStatistics(0, 1)
print('Band range: {minimum} - {maximum}'.format(maximum=band_max,minimum=band_min))
print('Band mean, stddev: {m}, {s}\n'.format(m=band_mean, s=band_stddev))

Band range: 0.33660000562668 - 0.015299990773201
Band mean, stddev: 0.049093857786703, 0.014083102996686



In [50]:
# read the band in the form of numpyarray
blue_data = blue.ReadAsArray()

print(blue_data)
print()
print('Blue band mean is: {m}'.format(m=blue_data.mean()))
print('Size is: {sz}'.format(sz=blue_data.shape))

[[-999. -999. -999. ... -999. -999. -999.]
 [-999. -999. -999. ... -999. -999. -999.]
 [-999. -999. -999. ... -999. -999. -999.]
 ...
 [-999. -999. -999. ... -999. -999. -999.]
 [-999. -999. -999. ... -999. -999. -999.]
 [-999. -999. -999. ... -999. -999. -999.]]

Blue band mean is: -27.97496795654297
Size is: (1770, 2607)


In [51]:
# Initialize a 3d array -- use the size properties of our image for portability!
image = np.zeros((raster.RasterYSize, raster.RasterXSize, raster.RasterCount))

# Loop over all bands in dataset
for b in range(raster.RasterCount):
    # Remember, GDAL index is on 1, but Python is on 0 -- so we add 1 for our GDAL calls
    band = raster.GetRasterBand(b + 1)
    
    # Read in the band's data into the third dimension of our array
    image[:, :, b] = band.ReadAsArray()

print(image)
print(image.dtype)

[[[-999. -999. -999. -999.]
  [-999. -999. -999. -999.]
  [-999. -999. -999. -999.]
  ...
  [-999. -999. -999. -999.]
  [-999. -999. -999. -999.]
  [-999. -999. -999. -999.]]

 [[-999. -999. -999. -999.]
  [-999. -999. -999. -999.]
  [-999. -999. -999. -999.]
  ...
  [-999. -999. -999. -999.]
  [-999. -999. -999. -999.]
  [-999. -999. -999. -999.]]

 [[-999. -999. -999. -999.]
  [-999. -999. -999. -999.]
  [-999. -999. -999. -999.]
  ...
  [-999. -999. -999. -999.]
  [-999. -999. -999. -999.]
  [-999. -999. -999. -999.]]

 ...

 [[-999. -999. -999. -999.]
  [-999. -999. -999. -999.]
  [-999. -999. -999. -999.]
  ...
  [-999. -999. -999. -999.]
  [-999. -999. -999. -999.]
  [-999. -999. -999. -999.]]

 [[-999. -999. -999. -999.]
  [-999. -999. -999. -999.]
  [-999. -999. -999. -999.]
  ...
  [-999. -999. -999. -999.]
  [-999. -999. -999. -999.]
  [-999. -999. -999. -999.]]

 [[-999. -999. -999. -999.]
  [-999. -999. -999. -999.]
  [-999. -999. -999. -999.]
  ...
  [-999. -999. -999. -99

In [52]:
raster.GetRasterBand(1).DataType


6

In [53]:

from osgeo import gdal_array

# DataType is a property of the individual raster bands
image_datatype = raster.GetRasterBand(1).DataType

# Allocate our array, but in a more efficient way
image_correct = np.zeros((raster.RasterYSize, raster.RasterXSize, raster.RasterCount),
                 dtype=gdal_array.GDALTypeCodeToNumericTypeCode(image_datatype))

# Loop over all bands in dataset
for b in range(raster.RasterCount):
    # Remember, GDAL index is on 1, but Python is on 0 -- so we add 1 for our GDAL calls
    band = raster.GetRasterBand(b + 1)
    
    # Read in the band's data into the third dimension of our array
    image_correct[:, :, b] = band.ReadAsArray()

print("Compare datatypes: ")
print("    when unspecified: {dt}".format(dt=image.dtype))
print("    when specified: {dt}".format(dt=image_correct.dtype))
print('Red band mean: {r}'.format(r=image[:, :, 2].mean()))
print('NIR band mean: {nir}'.format(nir=image[:, :, 3].mean()))

Compare datatypes: 
    when unspecified: float64
    when specified: float32
Red band mean: -27.942620814044673
NIR band mean: -27.87640348750272


In [54]:
b_red = 2
b_nir = 3

ndvi = (image[:, :, b_nir] - image[:, :, b_red]) / (image[:, :, b_red] + image[:, :, b_nir])

print(ndvi)
print('Maximum value of NDVI = {ndvi} '.format(ndvi=ndvi.max()) )

[[-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 ...
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]]
Maximum value of NDVI = 0.908464587950874 


In [55]:
ndvi = (image[:, :, b_nir] - image[:, :, b_red]) / \
        (image[:, :, b_nir] + image[:, :, b_red]).astype(np.float64)

print('NDVI matrix: ')
print(ndvi)

print('\nMax NDVI: {m}'.format(m=ndvi.max()))
print('Mean NDVI: {m}'.format(m=ndvi.mean()))
print('Median NDVI: {m}'.format(m=np.median(ndvi)))
print('Min NDVI: {m}'.format(m=ndvi.min()))

NDVI matrix: 
[[-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 ...
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]]

Max NDVI: 0.908464587950874
Mean NDVI: 0.2568754514932775
Median NDVI: 0.19104636375367037
Min NDVI: -0.4062500429942998


In [76]:
### Let's get starting with the vector dataset
dataset = ogr.Open('F:/works/practical/Dist-Boundary/Punjab Districts.shp')

# the driver of the shapefile 
driver = dataset.GetDriver()
print('Dataset driver is: {n}\n'.format(n=driver.name))

# How many layers contain in shapefile
layers = dataset.GetLayerCount()
print('Number of layers = {n}\n'.format(n=layers))

### What is the name of the 1 layer?
layer = dataset.GetLayerByIndex(0)
print('The layer is named: {n}\n'.format(n=layer.GetName()))

geometry = layer.GetGeomType()

# So we need to translate it to the name of the enum
geometry_name = ogr.GeometryTypeToName(geometry)
print("The layer's geometry is: {geom}\n".format(geom=geometry_name))

# Get the spatial reference
spatial_ref = layer.GetSpatialRef()

# Export this spatial reference to something we can read... like the Proj4
proj4 = spatial_ref.ExportToProj4()
print('Layer projection is: {proj4}\n'.format(proj4=proj4))

### How many features are in the layer?
feature_count = layer.GetFeatureCount()
print('Layer has {n} features\n'.format(n=feature_count))

### How many fields are in the shapefile, and what are their names?
# First we need to capture the layer definition
defn = layer.GetLayerDefn()

# How many fields
field_count = defn.GetFieldCount()
print('Layer has {n} fields'.format(n=field_count))

# What are their names?
print('Their names are: ')
for i in range(field_count):
    field_defn = defn.GetFieldDefn(i)
    print('\t{name} - {datatype}'.format(name=field_defn.GetName(),
                                         datatype=field_defn.GetTypeName()))

Dataset driver is: ESRI Shapefile

Number of layers = 1

The layer is named: Punjab Districts

The layer's geometry is: Polygon

Layer projection is: +proj=longlat +datum=WGS84 +no_defs 

Layer has 36 features

Layer has 2 fields
Their names are: 
	OBJECTID - Integer64
	Distt_name - String


In [75]:
     ### End chapter 1